export default {
  title: "Reports/Certificates/Siap Sekolah",
};

const Template = (args) => ({
  components: {
    KesiapanSekolah: () =>
      import("~/components/Reports/Certificates/SiapSekolah/KesiapanSekolah"),
  },
  template: "<KesiapanSekolah />",
  title: "Kesiapan Sekolah",
  created() {
    this.$store.commit("asesmenDetail/state", {
      key: "detail",
      val: args.data,
    });
  },
});

export const KesiapanSekolah = Template.bind({});
KesiapanSekolah.args = {
  data: {
    id: 2550,
    user_id: 0,
    assessment_id: 282,
    completed: 1,
    completed_at: "2022-09-01 14:24:23",
    created_at: "2022-09-01T14:22:20.000000Z",
    updated_at: "2022-09-02T12:17:59.000000Z",
    resume: null,
    result: null,
    assessment_slug: "sskb-ks",
    score_cumulative: 179,
    aspect_total: 5,
    aspect_finish: 5,
    emg_user_result_id: null,
    version: 0,
    score_raw: 61,
    talentics_id: 2986,
    duration: 3600000,
    started_at: "2022-09-01 14:22:24",
    response_style: 0,
    score_standard: 36,
    count_answer: 30,
    count_question: 50,
    result_number: "202209020002550",
    is_no_answer: 0,
    is_no_score: 1,
    aspectScores: [
      {
        id: 9713,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1361,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-bljr",
        score_total: 56,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9712,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1360,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-sos",
        score_total: 4,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9711,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1359,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-bhs",
        score_total: 1,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9709,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1352,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-mtr",
        score_total: 0,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9710,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1353,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-kog",
        score_total: 0,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
    ],
    camera_capture: [],
    exit_tabs: [
      {
        time_out: "2022-09-01 21:23:08",
        time_in: "2022-09-01 21:23:21",
        text: "out of focus.",
        text_en: "out of focus.",
      },
      {
        time_out: "2022-09-01 21:23:44",
        time_in: "2022-09-01 21:23:45",
        text: "out of focus.",
        text_en: "out of focus.",
      },
    ],
    misbehaviour: {
      category: {
        level1: 2,
        level2: 0,
        level3: 0,
        level4: 0,
      },
      total_score: 2,
      level: 0,
      color: "green",
    },
    verifications: null,
    score_benchmark: 0,
    score_benchmark_2: 0,
    score_benchmark_3: 0,
    score_benchmark_4: 0,
    custom_scores: [],
    assessment: {
      id: 282,
      name: "Siap Sekolah PAUD KB - Kesiapan Sekolah",
      description: "Asesmen Kesiapan Sekolah PAUD KB",
      slug: "sskb-ks",
      image_url: "https://picsum.photos/200",
      duration: 3600000,
      is_random: 0,
      is_per_aspect: 1,
      is_answer_random: 0,
      backable: 0,
      is_markable: 0,
      is_multiple_result: 0,
      is_selected_question_using_linked: 0,
      is_english: 0,
      is_dual_language: 0,
      is_using_speed_and_accuracy: 0,
      is_random_selected_question: 0,
      status_access: 0,
      question_grouping_count: 0,
      total_question_by_admin: 50,
      custom_scores: [],
      questions_count: 50,
    },
    name: "Siap Sekolah PAUD KB - Kesiapan Sekolah",
    score_percent: 36,
    result_content: [],
    result_content_multiple: [],
    result_static: [
      {
        id: 652,
        input_type: 0,
        form_name: "title_belum_siap_sekolah",
        content: "<p>Belum Siap Sekolah</p>",
      },
      {
        id: 653,
        input_type: 0,
        form_name: "description_belum_siap_sekolah",
        content:
          "<p>Saat ini, beberapa kemampuan dasar Ananda yang mendukungnya mengikuti kegiatan belajar mengajar di sekolah belum berkembang dengan optimal. Ananda perlu waktu untuk mengembangkan kemampuannya agar bisa bersekolah jenjang PAUD KB dengan nyaman dan optimal. Anda disarankan untuk menunda pendaftaran Ananda ke jenjang PAUD KB dan mengkonsultasikan hal ini kepada Tim Penerimaan Murid Baru Sekolah Murid Merdeka.</p>",
      },
      {
        id: 654,
        input_type: 0,
        form_name: "title_siap_sekolah_dengan_catatan",
        content: "<p>Siap Sekolah dengan Catatan</p>",
      },
      {
        id: 655,
        input_type: 0,
        form_name: "description_siap_sekolah_dengan_catatan",
        content:
          "<p>Saat ini, Ananda memiliki cukup keterampilan dasar yang akan mendukungnya mengikuti kegiatan belajar di sekolah. Meskipun demikian, Ananda masih perlu mengembangkan kemampuannya dalam aspek tertentu agar bisa bersekolah di jenjang PAUD KB dengan nyaman dan optimal. Anda dapat mengkonsultasikan hal ini kepada Tim Penerimaan Murid Baru Sekolah Murid Merdeka sebelum mendaftarkan Ananda ke jenjang PAUD KB.</p>",
      },
      {
        id: 656,
        input_type: 0,
        form_name: "title_siap_sekolah",
        content: "<p>Siap Sekolah</p>",
      },
      {
        id: 657,
        input_type: 0,
        form_name: "description_siap_sekolah",
        content:
          "<p>Secara umum, Ananda memiliki kemampuan dan keterampilan dasar yang akan membantuinya menyerap informasi, memahami konsep, dan mengikuti kegiatan belajar di sekolah. Kemampuan dan keterampilan dasar yang Ananda miliki dapat menunjang keberhasilannya mengikuti kegiatan belajar mengajar di jenjang PAUD KB. Oleh karena itu, Anda dapat langsung mendaftarkan Ananda di Sekolah Murid Merdeka pada jenjang PAUD KB.</p>",
      },
    ],
    group_results: [],
    aspect_results: [
      {
        id: 7960,
        user_id: 0,
        assessment_aspect_id: "1352",
        completed: 1,
        completed_at: "2022-09-01 14:24:23",
        created_at: "2022-09-01T14:22:22.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        norm_category_id: 1371,
        score_percent: 0,
        assessment_id: 282,
        assessment_aspect_slug: "ks-mtr",
        assessment_slug: "sskb-ks",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2986,
        symbol: null,
        category: 0,
        score_standard: 0,
        count_answer: 1,
        count_question: 10,
        duration: 0,
        started_at: "2022-09-01 14:22:24",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: 0,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1352,
          assessment_id: 282,
          name: "Kesiapan Fisik dan Motorik",
          description: null,
          slug: "ks-mtr",
          type: "non-cognitive",
          image_url:
            "https://stg-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVBIGV2BPBUDEEOMV%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T174658Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=ea5cb66ae786dece41aec1063f7eb2d671c5e7d07533ec1819ad7659ffd64a33",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 10,
          label_score_default: "",
          result: null,
          scale: "multiple3",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25595,
            form_name: "category_title",
            value: "Belum Siap Sekolah PAUD KB",
            type: 0,
          },
          {
            id: 25596,
            form_name: "content_summary",
            value:
              "Kemampuan Ananda dalam melakukan aktivitas yang membutuhkan kontrol dan koordinasi otot tubuh (motorik kasar) atau tangan dan jari (motorik halus) masih perlu banyak dilatih. Ananda disarankan untuk mengembangkan kemampuan motorik kasar dan halusnya sebelum memasuki jenjang PAUD KB.",
            type: 1,
          },
          {
            id: 25597,
            form_name: "values",
            value: "0",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
      {
        id: 7961,
        user_id: 0,
        assessment_aspect_id: "1353",
        completed: 1,
        completed_at: "2022-09-01 14:24:23",
        created_at: "2022-09-01T14:22:22.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        norm_category_id: 1374,
        score_percent: 0,
        assessment_id: 282,
        assessment_aspect_slug: "ks-kog",
        assessment_slug: "sskb-ks",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2986,
        symbol: null,
        category: 0,
        score_standard: 0,
        count_answer: 5,
        count_question: 10,
        duration: 0,
        started_at: "2022-09-01 14:22:28",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: 0,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1353,
          assessment_id: 282,
          name: "Kesiapan Kognitif",
          description: null,
          slug: "ks-kog",
          type: "non-cognitive",
          image_url:
            "https://stg-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVBIGV2BPBUDEEOMV%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T174658Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=ea5cb66ae786dece41aec1063f7eb2d671c5e7d07533ec1819ad7659ffd64a33",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 10,
          label_score_default: "",
          result: null,
          scale: "multiple4",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25604,
            form_name: "category_title",
            value: "Belum Siap Sekolah PAUD KB",
            type: 0,
          },
          {
            id: 25605,
            form_name: "content_summary",
            value:
              "Kemampuan Ananda untuk membangun pemahaman/wawasan mengenai dunia di sekitarnya masih perlu banyak dilatih. Hal yang perlu dilatih antara lain adalah kemampuan mengenali hal-hal di sekitar (objek maupun orang) beserta perbedaan dan persamaannya satu sama lain. Ananda disarankan untuk mengembangkan kemampuan-kemampuan tersebut sebelum memasuki jenjang PAUD KB.",
            type: 1,
          },
          {
            id: 25606,
            form_name: "values",
            value: "0",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
      {
        id: 7962,
        user_id: 0,
        assessment_aspect_id: "1359",
        completed: 1,
        completed_at: "2022-09-01 14:24:23",
        created_at: "2022-09-01T14:22:22.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        norm_category_id: 1377,
        score_percent: 17,
        assessment_id: 282,
        assessment_aspect_slug: "ks-bhs",
        assessment_slug: "sskb-ks",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2986,
        symbol: null,
        category: 0,
        score_standard: 17,
        count_answer: 6,
        count_question: 10,
        duration: 0,
        started_at: "2022-09-01 14:22:42",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: 1,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1359,
          assessment_id: 282,
          name: "Kesiapan Bahasa",
          description: null,
          slug: "ks-bhs",
          type: "non-cognitive",
          image_url:
            "https://stg-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVBIGV2BPBUDEEOMV%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T174658Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=ea5cb66ae786dece41aec1063f7eb2d671c5e7d07533ec1819ad7659ffd64a33",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 10,
          label_score_default: "",
          result: null,
          scale: "multiple3",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25643,
            form_name: "category_title",
            value: "Belum Siap Sekolah PAUD KB",
            type: 0,
          },
          {
            id: 25644,
            form_name: "content_summary",
            value:
              "Kemampuan bahasa Ananda masih perlu banyak dilatih. Sebelum memasuki jenjang PAUD KB, Ananda perlu mengembangkan kemampuan bahasa, contohnya menyebutkan nama-nama objek familiar dan menggunakan kalimat-kalimat singkat maupun coretan/simbol untuk menggambarkan pengalaman atau hal-hal di sekitar.",
            type: 1,
          },
          {
            id: 25645,
            form_name: "values",
            value: "0",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
      {
        id: 7963,
        user_id: 0,
        assessment_aspect_id: "1360",
        completed: 1,
        completed_at: "2022-09-01 14:24:23",
        created_at: "2022-09-01T14:22:22.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        norm_category_id: 1382,
        score_percent: 80,
        assessment_id: 282,
        assessment_aspect_slug: "ks-sos",
        assessment_slug: "sskb-ks",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2986,
        symbol: null,
        category: 0,
        score_standard: 80,
        count_answer: 1,
        count_question: 10,
        duration: 0,
        started_at: "2022-09-01 14:22:52",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: 4,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1360,
          assessment_id: 282,
          name: "Kesiapan Sosial-Emosional",
          description: null,
          slug: "ks-sos",
          type: "non-cognitive",
          image_url:
            "https://stg-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVBIGV2BPBUDEEOMV%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T174658Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=ea5cb66ae786dece41aec1063f7eb2d671c5e7d07533ec1819ad7659ffd64a33",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 10,
          label_score_default: "",
          result: null,
          scale: "likert7",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25658,
            form_name: "category_title",
            value: "Siap Sekolah PAUD KB",
            type: 0,
          },
          {
            id: 25659,
            form_name: "content_summary",
            value:
              "Kemampuan sosial-emosional Ananda sudah memadai untuk bersosialisasi di jenjang PAUD KB. Ia sudah dapat melakukan kegiatan bantu diri, mengekspresikan emosi, dan menjalin relasi dengan teman sebaya. Kemampuan-kemampuan tersebut menjadi bekal yang mendukungnya untuk bersosialisasi di jenjang PAUD KB dengan nyaman.",
            type: 1,
          },
          {
            id: 25660,
            form_name: "values",
            value: "2",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
      {
        id: 7964,
        user_id: 0,
        assessment_aspect_id: "1361",
        completed: 1,
        completed_at: "2022-09-01 14:24:23",
        created_at: "2022-09-01T14:22:22.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        norm_category_id: 1385,
        score_percent: 82,
        assessment_id: 282,
        assessment_aspect_slug: "ks-bljr",
        assessment_slug: "sskb-ks",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2986,
        symbol: null,
        category: 0,
        score_standard: 82,
        count_answer: 17,
        count_question: 10,
        duration: 0,
        started_at: "2022-09-01 14:22:59",
        is_no_answer: 0,
        is_no_score: 0,
        score_raw: 56,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1361,
          assessment_id: 282,
          name: "Pendekatan Belajar",
          description: null,
          slug: "ks-bljr",
          type: "non-cognitive",
          image_url:
            "https://stg-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVBIGV2BPBUDEEOMV%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T174658Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=ea5cb66ae786dece41aec1063f7eb2d671c5e7d07533ec1819ad7659ffd64a33",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 10,
          label_score_default: "",
          result: null,
          scale: "likert4",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25667,
            form_name: "category_title",
            value: "Siap Sekolah PAUD KB",
            type: 0,
          },
          {
            id: 25668,
            form_name: "content_summary",
            value:
              "Secara umum, Ananda sudah memiliki keterampilan-keterampilan dasar yang dibutuhkan untuk mendukung proses belajar. Keterampilan tersebut meliputi rasa ingin tahu, kegigihan, kemampuan memusatkan perhatian, kreativitas, kemandirian mengerjakan tugas, keterbukaan pada hal baru, keteraturan, inisiatif, pemecahan masalah, serta kemampuan berkomunikasi dan bekerja sama dalam kelompok. Keterampilan dasar belajar yang dimilikinya akan membantu Ananda untuk beradaptasi dengan baik saat menghadapi tuntutan akademis di sekolah",
            type: 1,
          },
          {
            id: 25669,
            form_name: "values",
            value: "2",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
    ],
    response_style_content: null,
    narration: null,
    narration_en: null,
    user_logs: [
      {
        time: "2022-09-01 21:22:24",
        text: "Memulai Tes Siap Sekolah PAUD KB - Kesiapan Sekolah",
        text_en: "Start Test Siap Sekolah PAUD KB - Kesiapan Sekolah",
      },
      {
        time: "2022-09-01 21:22:24",
        text: "Memulai Aspect Kesiapan Fisik dan Motorik",
        text_en: "Start Aspect Kesiapan Fisik dan Motorik",
      },
      {
        time: "2022-09-01 21:22:28",
        text: "Selesai Aspect Kesiapan Fisik dan Motorik",
        text_en: "Finish Aspect Kesiapan Fisik dan Motorik",
      },
      {
        time: "2022-09-01 21:22:28",
        text: "Memulai Aspect Kesiapan Kognitif",
        text_en: "Start Aspect Kesiapan Kognitif",
      },
      {
        time: "2022-09-01 21:22:42",
        text: "Selesai Aspect Kesiapan Kognitif",
        text_en: "Finish Aspect Kesiapan Kognitif",
      },
      {
        time: "2022-09-01 21:22:42",
        text: "Memulai Aspect Kesiapan Bahasa",
        text_en: "Start Aspect Kesiapan Bahasa",
      },
      {
        time: "2022-09-01 21:22:52",
        text: "Selesai Aspect Kesiapan Bahasa",
        text_en: "Finish Aspect Kesiapan Bahasa",
      },
      {
        time: "2022-09-01 21:22:52",
        text: "Memulai Aspect Kesiapan Sosial-Emosional",
        text_en: "Start Aspect Kesiapan Sosial-Emosional",
      },
      {
        time: "2022-09-01 21:22:59",
        text: "Selesai Aspect Kesiapan Sosial-Emosional",
        text_en: "Finish Aspect Kesiapan Sosial-Emosional",
      },
      {
        time: "2022-09-01 21:22:59",
        text: "Memulai Aspect Pendekatan Belajar",
        text_en: "Start Aspect Pendekatan Belajar",
      },
      {
        time: "2022-09-01 21:24:23",
        text: "Selesai Aspect Pendekatan Belajar",
        text_en: "Finish Aspect Pendekatan Belajar",
      },
      {
        time: "2022-09-01 21:24:23",
        text: "Selesai Tes Siap Sekolah PAUD KB - Kesiapan Sekolah",
        text_en: "Finish Test Siap Sekolah PAUD KB - Kesiapan Sekolah",
      },
    ],
    user: {
      name: "Alfi Farikh",
    },
    aspect_scores: [
      {
        id: 9713,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1361,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-bljr",
        score_total: 56,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9712,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1360,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-sos",
        score_total: 4,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9711,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1359,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-bhs",
        score_total: 1,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9709,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1352,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-mtr",
        score_total: 0,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
      {
        id: 9710,
        user_id: 0,
        assessment_id: 282,
        assessment_aspect_id: 1353,
        assessment_slug: "sskb-ks",
        assessment_aspect_slug: "ks-kog",
        score_total: 0,
        score_label: "",
        created_at: "2022-09-01T14:24:23.000000Z",
        updated_at: "2022-09-01T14:24:23.000000Z",
        talentics_id: 2986,
      },
    ],
  },
};
