export default {
  title: "Reports/Certificates/Siap Sekolah",
};

const Template = (args) => ({
  components: {
    KesiapanKeluarga: () =>
      import("~/components/Reports/Certificates/SiapSekolah/KesiapanKeluarga"),
  },
  template: "<KesiapanKeluarga />",
  title: "Kesiapan Keluarga",
  created() {
    this.$store.commit("asesmenDetail/state", {
      key: "detail",
      val: args.data,
    });
  },
});

export const KesiapanKeluarga = Template.bind({});
KesiapanKeluarga.args = {
  data: {
    id: 1942,
    user_id: 0,
    assessment_id: 304,
    completed: 1,
    completed_at: "2022-08-25 09:18:52",
    created_at: "2022-08-25T09:17:42.000000Z",
    updated_at: "2022-08-25T09:18:52.000000Z",
    resume: null,
    result: null,
    assessment_slug: "ss6-kk",
    score_cumulative: -1,
    aspect_total: 1,
    aspect_finish: 1,
    emg_user_result_id: null,
    version: 0,
    score_raw: 175,
    talentics_id: 2811,
    duration: 1740000,
    started_at: "2022-08-25 09:17:47",
    response_style: 0,
    score_standard: 0,
    count_answer: 33,
    count_question: 33,
    result_number: "202208250001942",
    is_no_answer: 0,
    is_no_score: 0,
    aspectScores: [
      {
        id: 10631,
        user_id: 0,
        assessment_id: 304,
        assessment_aspect_id: 1408,
        assessment_slug: "ss6-kk",
        assessment_aspect_slug: "ss6-kk-siapklg",
        score_total: 175,
        score_label: "",
        created_at: "2022-08-25T09:18:52.000000Z",
        updated_at: "2022-08-25T09:18:52.000000Z",
        talentics_id: 2811,
      },
    ],
    camera_capture: [],
    exit_tabs: [],
    misbehaviour: {
      category: {
        level1: 0,
        level2: 0,
        level3: 0,
        level4: 0,
      },
      total_score: 0,
      level: 0,
      color: "green",
    },
    verifications: null,
    score_benchmark: 0,
    score_benchmark_2: 0,
    score_benchmark_3: 0,
    score_benchmark_4: 0,
    custom_scores: [],
    assessment: {
      id: 304,
      name: "Siap Sekolah SD Kelas 6 - Kesiapan Keluarga",
      description: "Asesmen Kesiapan Keluarga",
      slug: "ss6-kk",
      image_url: "https://picsum.photos/200",
      duration: 1800000,
      is_random: 0,
      is_per_aspect: 0,
      is_answer_random: 0,
      backable: 0,
      is_markable: 0,
      is_multiple_result: 0,
      is_selected_question_using_linked: 0,
      is_english: 0,
      is_dual_language: 0,
      is_using_speed_and_accuracy: 0,
      is_random_selected_question: 0,
      status_access: 0,
      question_grouping_count: 0,
      total_question_by_admin: 33,
      custom_scores: [
        {
          id: 10,
          assessment_id: 304,
          custom_score_id: 1,
          created_at: "2022-08-31T03:52:21.000000Z",
          updated_at: "2022-08-31T03:52:21.000000Z",
          custom_score: {
            id: 1,
            name: "Score Directive",
            code: "disc_d",
            type: "DISC",
            created_at: "2021-01-20T05:47:06.000000Z",
            updated_at: "2021-02-03T10:19:31.000000Z",
            components: [
              {
                id: 1,
                custom_score_id: 1,
                name: "Holder Competence",
                weight: 1,
                pole: "normal",
                score_type: "percent",
                cut_off: 83,
                created_at: "2021-01-20T06:24:21.000000Z",
                updated_at: "2021-01-21T09:47:38.000000Z",
              },
              {
                id: 2,
                custom_score_id: 1,
                name: "Holder Achievement",
                weight: 1,
                pole: "normal",
                score_type: "percent",
                cut_off: 83,
                created_at: "2021-01-21T09:49:07.000000Z",
                updated_at: "2021-01-21T09:49:07.000000Z",
              },
              {
                id: 3,
                custom_score_id: 1,
                name: "Holder Ascendance",
                weight: 1,
                pole: "normal",
                score_type: "percent",
                cut_off: 83,
                created_at: "2021-01-21T09:49:36.000000Z",
                updated_at: "2021-01-21T09:49:36.000000Z",
              },
              {
                id: 4,
                custom_score_id: 1,
                name: "Holder Compliance",
                weight: 1,
                pole: "inverse",
                score_type: "percent",
                cut_off: 80,
                created_at: "2021-01-21T09:50:31.000000Z",
                updated_at: "2021-01-21T10:27:50.000000Z",
              },
              {
                id: 5,
                custom_score_id: 1,
                name: "Holder Tendermindedness",
                weight: 1,
                pole: "inverse",
                score_type: "percent",
                cut_off: 80,
                created_at: "2021-01-21T09:51:30.000000Z",
                updated_at: "2021-01-21T10:27:59.000000Z",
              },
              {
                id: 6,
                custom_score_id: 1,
                name: "Holder Insecurity",
                weight: 1,
                pole: "inverse",
                score_type: "percent",
                cut_off: 80,
                created_at: "2021-01-21T09:51:50.000000Z",
                updated_at: "2021-01-21T10:28:06.000000Z",
              },
            ],
          },
          aspect_components: [],
        },
      ],
      questions_count: 33,
    },
    name: "Siap Sekolah SD Kelas 6 - Kesiapan Keluarga",
    score_percent: -1,
    result_content: [
      {
        id: 25477,
        form_name: "category_title",
        value: "Daring Rutin",
        type: 0,
      },
      {
        id: 25478,
        form_name: "info_description",
        value:
          "Keluarga anda siap untuk mendukung anak anda untuk belajar secara daring rutin di Sekolah Murid Merdeka|Dengan mempertimbangkan sumber daya yang dimiliki orang tua/wali murid, baik dari segi waktu untuk terlibat aktif dalam pendampingan belajar anak, penerimaan diri terhadap pemanfaatan teknologi, maupun keyakinan terhadap efektivitas proses pembelajaran yang akan berlangsung dengan metode blended learning, keluarga disarankan untuk mendaftarkan Ananda untuk belajar di Sekolah Murid Merdeka pada program belajar daring rutin.",
        type: 2,
      },
      {
        id: 25479,
        form_name: "category_title_en",
        value: null,
        type: 0,
      },
      {
        id: 25480,
        form_name: "info_description_en",
        value: null,
        type: 2,
      },
    ],
    result_content_multiple: [],
    result_static: [],
    group_results: [],
    aspect_results: [
      {
        id: 7241,
        user_id: 0,
        assessment_aspect_id: "1408",
        completed: 1,
        completed_at: "2022-08-25 09:18:52",
        created_at: "2022-08-25T09:17:49.000000Z",
        updated_at: "2022-08-25T09:18:52.000000Z",
        norm_category_id: null,
        score_percent: -1,
        assessment_id: 304,
        assessment_aspect_slug: "ss6-kk-siapklg",
        assessment_slug: "ss6-kk",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2811,
        symbol: null,
        category: 0,
        score_standard: 0,
        count_answer: 33,
        count_question: 33,
        duration: 0,
        started_at: null,
        is_no_answer: 0,
        is_no_score: 0,
        score_raw: 175,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1408,
          assessment_id: 304,
          name: "Kesiapan Keluarga",
          description: null,
          slug: "ss6-kk-siapklg",
          type: "non-cognitive",
          image_url:
            "https://dev-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWCHSRR2INJJO4T7J%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T174823Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=1218a19c81f347a82fa89e5bafac25cb2b9f71f7495357eabdfc5a7d9d64f8c3",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 33,
          label_score_default: "",
          result: null,
          scale: "likert",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [],
        result_static: [],
        score_category: 0,
      },
    ],
    response_style_content: null,
    narration: null,
    narration_en: null,
    user_logs: [
      {
        time: "2022-08-25 16:17:47",
        text: "Memulai Tes Siap Sekolah SD Kelas 6 - Kesiapan Keluarga",
        text_en: "Start Test Siap Sekolah SD Kelas 6 - Kesiapan Keluarga",
      },
      {
        time: "2022-08-25 16:18:51",
        text: "Selesai Tes Siap Sekolah SD Kelas 6 - Kesiapan Keluarga",
        text_en: "Finish Test Siap Sekolah SD Kelas 6 - Kesiapan Keluarga",
      },
    ],
    user: {
      name: "Ghany Abdillah Ersa",
    },
    aspect_scores: [
      {
        id: 10631,
        user_id: 0,
        assessment_id: 304,
        assessment_aspect_id: 1408,
        assessment_slug: "ss6-kk",
        assessment_aspect_slug: "ss6-kk-siapklg",
        score_total: 175,
        score_label: "",
        created_at: "2022-08-25T09:18:52.000000Z",
        updated_at: "2022-08-25T09:18:52.000000Z",
        talentics_id: 2811,
      },
    ],
  },
};
