export default {
  title: "Reports/Certificates/Siap Sekolah",
};

const Template = (args) => ({
  components: {
    ReportTumbuhKembang: () =>
      import("~/components/Reports/Certificates/SiapSekolah/TumbuhKembangAnak"),
  },
  template: "<ReportTumbuhKembang />",
  title: "Tumbuh Kembang Anak",
  created() {
    this.$store.commit("asesmenDetail/state", {
      key: "detail",
      val: args.data,
    });
  },
});

export const TumbuhKembangAnak = Template.bind({});
TumbuhKembangAnak.args = {
  data: {
    id: 1975,
    user_id: 0,
    assessment_id: 283,
    completed: 1,
    completed_at: "2022-08-29 05:14:37",
    created_at: "2022-08-29T05:14:05.000000Z",
    updated_at: "2022-08-29T05:14:37.000000Z",
    resume: null,
    result: null,
    assessment_slug: "sskb-tk",
    score_cumulative: 30,
    aspect_total: 4,
    aspect_finish: 4,
    emg_user_result_id: null,
    version: 0,
    score_raw: 11,
    talentics_id: 2822,
    duration: 3600000,
    started_at: "2022-08-29 05:14:13",
    response_style: 0,
    score_standard: 8,
    count_answer: 6,
    count_question: 41,
    result_number: "202208290001975",
    is_no_answer: 0,
    is_no_score: 1,
    aspectScores: [
      {
        id: 10871,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1340,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-bhs",
        score_total: 6,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
      {
        id: 10870,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1339,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-kog",
        score_total: 3,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
      {
        id: 10872,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1341,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-sos",
        score_total: 3,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
      {
        id: 10869,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1338,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-mtr",
        score_total: -1,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
    ],
    camera_capture: [],
    exit_tabs: [],
    misbehaviour: {
      category: {
        level1: 0,
        level2: 0,
        level3: 0,
        level4: 0,
      },
      total_score: 0,
      level: 0,
      color: "green",
    },
    verifications: null,
    score_benchmark: 0,
    score_benchmark_2: 0,
    score_benchmark_3: 0,
    score_benchmark_4: 0,
    custom_scores: [],
    assessment: {
      id: 283,
      name: "Siap Sekolah PAUD KB - Tumbuh Kembang",
      description: "Asesmen Tumbuh Kembang Anak\r\nPAUD KB",
      slug: "sskb-tk",
      image_url: "https://picsum.photos/200",
      duration: 3600000,
      is_random: 0,
      is_per_aspect: 1,
      is_answer_random: 0,
      backable: 0,
      is_markable: 0,
      is_multiple_result: 0,
      is_selected_question_using_linked: 0,
      is_english: 0,
      is_dual_language: 0,
      is_using_speed_and_accuracy: 0,
      is_random_selected_question: 0,
      status_access: 0,
      question_grouping_count: 0,
      total_question_by_admin: 41,
      custom_scores: [],
      questions_count: 41,
    },
    name: "Siap Sekolah PAUD KB - Tumbuh Kembang",
    score_percent: 8,
    result_content: [],
    result_content_multiple: [],
    result_static: [
      {
        id: 659,
        input_type: 0,
        form_name: "title_belum_berkembang_sesuai_usia",
        content: "<p>Belum Berkembang Sesuai Usia</p>",
      },
      {
        id: 660,
        input_type: 0,
        form_name: "description_belum_berkembang_sesuai_usia",
        content:
          "<p>Berdasarkan asesmen ini, kondisi perkembangan Ananda tampak belum sepenuhnya berkembang sesuai dengan usianya. Silakan berkonsultasi dengan Psikolog/Dokter Anak dan Tim Penerimaan Murid Baru Sekolah Murid Merdeka mengenai kondisi tumbuh kembang Ananda sebelum mendaftarkannya pada jenjang PAUD KB.</p>",
      },
      {
        id: 661,
        input_type: 0,
        form_name: "title_berkembang_sesuai_usia",
        content: "<p>Berkembang Sesuai Usia</p>",
      },
      {
        id: 662,
        input_type: 0,
        form_name: "description_berkembang_sesuai_usia",
        content:
          "<p>Berdasarkan asesmen ini, tampak bahwa perkembangan Ananda telah sesuai dengan usianya. Hal ini diperkirakan akan menjadi bekal untuk menudkung Ananda bersekolah di jenjang PAUD KB. Anda dapat mendaftarkan Ananda untuk bersekolah di Sekolah Murid Merdeka pada jenjang PAUD KB.</p>",
      },
    ],
    group_results: [],
    aspect_results: [
      {
        id: 7478,
        user_id: 0,
        assessment_aspect_id: "1338",
        completed: 1,
        completed_at: "2022-08-29 05:14:37",
        created_at: "2022-08-29T05:14:07.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        norm_category_id: 1369,
        score_percent: 0,
        assessment_id: 283,
        assessment_aspect_slug: "sskb-tk-mtr",
        assessment_slug: "sskb-tk",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2822,
        symbol: null,
        category: 0,
        score_standard: 0,
        count_answer: 1,
        count_question: 15,
        duration: 0,
        started_at: "2022-08-29 05:14:13",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: -1,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1338,
          assessment_id: 283,
          name: "Perkembangan Fisik dan Motorik",
          description: null,
          slug: "sskb-tk-mtr",
          type: "non-cognitive",
          image_url:
            "https://dev-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWCHSRR2INJJO4T7J%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T162400Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=320e631043d259862739fd6e3928d34c37f17c18f3a5095672c126d355d6d9ed",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 15,
          label_score_default: "",
          result: null,
          scale: "multiple2",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25777,
            form_name: "category_title",
            value: "Belum Berkembang Sesuai Usia",
            type: 0,
          },
          {
            id: 25778,
            form_name: "content_summary",
            value:
              "Terdapat beberapa aspek fisik dan motorik yang belum berkembang serta berfungsi dengan optimal sesuai perkembangan murid PAUD KB pada umumnya. Hal ini dapat mempengaruhi Ananda dalam melakukan aktivitas di sekolah maupun dalam kehidupan sehari-hari. Ananda disarankan untuk mengikuti pemeriksaan lebih lanjut yang meliputi aspek konsistensi tingkat pertumbuhan fisik, keberfungsian tubuh, kebugaran fisik, dan kelancaran dalam melakukan gerakan sederhana yang membutuhkan keseimbangan.",
            type: 1,
          },
          {
            id: 25779,
            form_name: "Values",
            value: "0",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
      {
        id: 7479,
        user_id: 0,
        assessment_aspect_id: "1339",
        completed: 1,
        completed_at: "2022-08-29 05:14:37",
        created_at: "2022-08-29T05:14:07.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        norm_category_id: 1371,
        score_percent: 12,
        assessment_id: 283,
        assessment_aspect_slug: "sskb-tk-kog",
        assessment_slug: "sskb-tk",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2822,
        symbol: null,
        category: 0,
        score_standard: 12,
        count_answer: 2,
        count_question: 4,
        duration: 0,
        started_at: "2022-08-29 05:14:19",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: 3,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1339,
          assessment_id: 283,
          name: "Perkembangan Kognitif",
          description: null,
          slug: "sskb-tk-kog",
          type: "non-cognitive",
          image_url:
            "https://dev-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWCHSRR2INJJO4T7J%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T162400Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=320e631043d259862739fd6e3928d34c37f17c18f3a5095672c126d355d6d9ed",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 4,
          label_score_default: "",
          result: null,
          scale: "likert",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25793,
            form_name: "category_title",
            value: "Belum Berkembang Sesuai Usia",
            type: 0,
          },
          {
            id: 25794,
            form_name: "content_summary",
            value:
              "Pada beberapa aspek, perkembangan kognitif Ananda belum berkembang sesuai dengan perkembangan siswa PAUD KB pada umumnya. Ananda disarankan untuk mengikuti pemeriksaan lebih lanjut yang dapat memberi informasi lebih detail mengenai kemampuan Ananda mengenali diri dan keluarga, mengenali dan membedakan objek di sekitar, atau menunjukkan pemikiran imajinatif dengan bermain peran dan berandai-andai.",
            type: 1,
          },
          {
            id: 25795,
            form_name: "Values",
            value: "0",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
      {
        id: 7480,
        user_id: 0,
        assessment_aspect_id: "1340",
        completed: 1,
        completed_at: "2022-08-29 05:14:37",
        created_at: "2022-08-29T05:14:07.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        norm_category_id: 1373,
        score_percent: 8,
        assessment_id: 283,
        assessment_aspect_slug: "sskb-tk-bhs",
        assessment_slug: "sskb-tk",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2822,
        symbol: null,
        category: 0,
        score_standard: 8,
        count_answer: 2,
        count_question: 16,
        duration: 0,
        started_at: "2022-08-29 05:14:27",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: 6,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1340,
          assessment_id: 283,
          name: "Perkembangan Bahasa",
          description: null,
          slug: "sskb-tk-bhs",
          type: "non-cognitive",
          image_url:
            "https://dev-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWCHSRR2INJJO4T7J%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T162400Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=320e631043d259862739fd6e3928d34c37f17c18f3a5095672c126d355d6d9ed",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 16,
          label_score_default: "",
          result: null,
          scale: "multiple3",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25799,
            form_name: "category_title",
            value: "Belum Berkembang Sesuai Usia",
            type: 0,
          },
          {
            id: 25800,
            form_name: "content_summary",
            value:
              "Pada beberapa area, kemampuan bahasa Ananda belum berkembang sesuai dengan perkembangan siswa PAUD KB pada umumnya. Ananda disarankan untuk mengikuti pemeriksaan lebih lanjut yang dapat memberi informasi lebih detail mengenai kemampuan Ananda mengenali dan menyebutkan nama sendiri serta hal lain di sekitarnya (objek atau orang terdekat) dengan kata-kata maupun coretan/simbol, merespon panggilan dan instruksi sederhana, menyampaikan suatu hal (keinginan/pengalaman) dengan kalimat singkat, memahami alur suatu cerita, dan menunjukkan ketertarikan pada bacaan.",
            type: 1,
          },
          {
            id: 25801,
            form_name: "Values",
            value: "0",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
      {
        id: 7481,
        user_id: 0,
        assessment_aspect_id: "1341",
        completed: 1,
        completed_at: "2022-08-29 05:14:37",
        created_at: "2022-08-29T05:14:07.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        norm_category_id: 1375,
        score_percent: 10,
        assessment_id: 283,
        assessment_aspect_slug: "sskb-tk-sos",
        assessment_slug: "sskb-tk",
        version: 0,
        emg_user_result_id: null,
        assessment_result_id: null,
        talentics_id: 2822,
        symbol: null,
        category: 0,
        score_standard: 10,
        count_answer: 1,
        count_question: 6,
        duration: 0,
        started_at: "2022-08-29 05:14:34",
        is_no_answer: 0,
        is_no_score: 1,
        score_raw: 3,
        detail: null,
        norm_category_show: false,
        norm_category: null,
        aspect: {
          id: 1341,
          assessment_id: 283,
          name: "Perkembangan Sosial-Emosional",
          description: null,
          slug: "sskb-tk-sos",
          type: "non-cognitive",
          image_url:
            "https://dev-talentics-storage.s3.ap-southeast-1.amazonaws.com/1?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWCHSRR2INJJO4T7J%2F20220904%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220904T162400Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Signature=320e631043d259862739fd6e3928d34c37f17c18f3a5095672c126d355d6d9ed",
          duration: 0,
          is_random: 0,
          is_unrandom_selected_question: 0,
          group: null,
          is_answer_random: 0,
          weight_score: 1,
          symbol: null,
          question_grouping_count: 0,
          total_question_by_admin: 6,
          label_score_default: "",
          result: null,
          scale: "likert7",
        },
        group: null,
        type: "non-cognitive",
        indicator_results: [],
        result_content: [
          {
            id: 25805,
            form_name: "category_title",
            value: "Belum Berkembang Sesuai Usia",
            type: 0,
          },
          {
            id: 25806,
            form_name: "content_summary",
            value:
              "Pada beberapa area, kemampuan sosial-emosional Ananda belum berkembang sesuai dengan perkembangan siswa PAUD KB pada umumnya. Belum berkembangnya kemampuan tersebut dapat memengaruhi penyesuaian diri Ananda di lingkungan sosial, termasuk di sekolah. Ananda disarankan untuk mengikuti pemeriksaan lebih lanjut yang dapat memberi informasi lebih detail mengenai kemampuan Ananda menunjukan emosi yang tepat sesuai kondisi yang sedang dialami, mengenali emosi orang lain, melakukan aktivitas untuk memenuhi kebutuhan dasar di usianya, serta mengenali gender dan siapa dirinya.",
            type: 1,
          },
          {
            id: 25807,
            form_name: "Values",
            value: "0",
            type: 0,
          },
        ],
        result_static: [],
        score_category: 0,
      },
    ],
    response_style_content: null,
    narration: null,
    narration_en: null,
    user_logs: [
      {
        time: "2022-08-29 12:14:13",
        text: "Memulai Tes Siap Sekolah PAUD KB - Tumbuh Kembang",
        text_en: "Start Test Siap Sekolah PAUD KB - Tumbuh Kembang",
      },
      {
        time: "2022-08-29 12:14:13",
        text: "Memulai Aspect Perkembangan Fisik dan Motorik",
        text_en: "Start Aspect Perkembangan Fisik dan Motorik",
      },
      {
        time: "2022-08-29 12:14:19",
        text: "Selesai Aspect Perkembangan Fisik dan Motorik",
        text_en: "Finish Aspect Perkembangan Fisik dan Motorik",
      },
      {
        time: "2022-08-29 12:14:19",
        text: "Memulai Aspect Perkembangan Kognitif",
        text_en: "Start Aspect Perkembangan Kognitif",
      },
      {
        time: "2022-08-29 12:14:26",
        text: "Selesai Aspect Perkembangan Kognitif",
        text_en: "Finish Aspect Perkembangan Kognitif",
      },
      {
        time: "2022-08-29 12:14:26",
        text: "Memulai Aspect Perkembangan Bahasa",
        text_en: "Start Aspect Perkembangan Bahasa",
      },
      {
        time: "2022-08-29 12:14:34",
        text: "Selesai Aspect Perkembangan Bahasa",
        text_en: "Finish Aspect Perkembangan Bahasa",
      },
      {
        time: "2022-08-29 12:14:34",
        text: "Memulai Aspect Perkembangan Sosial-Emosional",
        text_en: "Start Aspect Perkembangan Sosial-Emosional",
      },
      {
        time: "2022-08-29 12:14:36",
        text: "Selesai Aspect Perkembangan Sosial-Emosional",
        text_en: "Finish Aspect Perkembangan Sosial-Emosional",
      },
      {
        time: "2022-08-29 12:14:36",
        text: "Selesai Tes Siap Sekolah PAUD KB - Tumbuh Kembang",
        text_en: "Finish Test Siap Sekolah PAUD KB - Tumbuh Kembang",
      },
    ],
    user: {
      name: "Alfi Bocil",
      gender: "M",
      birthdate: "2000-12-12",
    },
    aspect_scores: [
      {
        id: 10871,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1340,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-bhs",
        score_total: 6,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
      {
        id: 10870,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1339,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-kog",
        score_total: 3,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
      {
        id: 10872,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1341,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-sos",
        score_total: 3,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
      {
        id: 10869,
        user_id: 0,
        assessment_id: 283,
        assessment_aspect_id: 1338,
        assessment_slug: "sskb-tk",
        assessment_aspect_slug: "sskb-tk-mtr",
        score_total: -1,
        score_label: "",
        created_at: "2022-08-29T05:14:37.000000Z",
        updated_at: "2022-08-29T05:14:37.000000Z",
        talentics_id: 2822,
      },
    ],
  },
};
